### PR TITLE
Add scaffold for person model

### LINKED ISSUE #1: Manual Data Input - Formular Eingabe zu Datenbank Pipeline
We need a way to create & update the database via an API endpoint. 

## Requirements
  - 3 Formulare für 3 Datenbanken, jeweils alle wichtigen Attribute abfragen
  - Pipeline zur Einspeisung in Datenbank (zB Formular zu CSV, CSV zu Datenbank)

## Notes
  - gleich in Ruby als Funktion: Daten anlegen, editieren
  - Absprache mit Datenbank Team, bei Erstellung der Datenbank, können auch die Formulare generiert werden
  - **Absprache mit UI Team**, wo kann so eine Editierfunktion sein?
  - Unterseite gleich die Seite zum editieren
  - Formularempfehlung: Google Forms, mit AppsScript ist man flexibel, wie man die Daten des Formulars verarbeitet
  - **Absprache mit Datenbank Team** über die wichtigen Attribute (zB auch Bilder?, Bilder hosten und Link in Datenbank?)
  - in Zukunft sollen auf diese Weise die Räume eingetragen werden

### PR DESCRIPTION
**Pull request by kpostnov**
Closes #1.

### CODE REVIEW

**Review by FranzSw — CHANGES_REQUESTED** [review]
Test automation

**Review by FranzSw — APPROVED** [review]
Looks good to me, so that we can start working on parsing data.

@hpi-swt2/br21 You could update this model in the future.

**Comment by chrisma** [comment]
Hi! How does this `Person` model relate to the existing `User` (that is also used to sign in and receives an email and name from the [HPI OIDC service](https://oidc.hpi.de))?

**Comment by FranzSw** [comment]
@chrisma The Person model is for now what any user is able to search for. In the future this could be linked to the User model e.g. via email. We don't want to find users but people on the campus.

**Comment by cdfhalle** [comment]
What about the errors in the pipeline, could you fix them first?

**Comment by chrisma** [comment]
> What about the errors in the pipeline, could you fix them first?

Currently, merging is blocked due to an outstanding requested review. Please don't let the CodeFactor checks slow you down, they are more for information and do not block merging PRs.

**Comment by FranzSw** [comment]
Person model is now merged by the BR team

**Pull request closed without merging**
