### PR TITLE
180 unified navigation view

### LINKED ISSUE #180: Unified design of the navigation view
As a User I want to have a unified layout of the navigation. Currently there is a location overview that does not change if I want to start the navigation to this location. The current layout of the navigation panel at the top right corner it's also very different from the layout of the rest of the application. I would like this layout to be changed and fitted to the bottom of the screen. Consistency is the goal, of course especially in the mobile view. So it might be useful to look at the current implementation of the location overview. 
image

### PR DESCRIPTION
**Pull request by felix-20**
This PR makes the navigation view look more like the existing map popup.
closes #180

### CODE REVIEW

**Review by ldreessen — DISMISSED** [review]
lgtm

**Review by NikkelM — CHANGES_REQUESTED** [review]
Looks nice, just two changes should be adressed:
image
If you look at the image, you can see that the result of the autocomplete is placed under the navigation pane (I did this by entering "HPI" in the search bar and pressing enter once). The results should be displayed on top of the pane so users can choose from the results.
Additionally, when clicking on the map without the navigation pane opened, the navigation starts, but the pane doesn't open, so that should also be addressed.

**Comment by felix-20** [comment]
@NikkelM we implemented this in e48eb43

> Looks nice, just two changes should be adressed: image If you look at the image, you can see that the result of the autocomplete is placed under the navigation pane (I did this by entering "HPI" in the search bar and pressing enter once). The results should be displayed on top of the pane so users can choose from the results. Additionally, when clicking on the map without the navigation pane opened, the navigation starts, but the pane doesn't open, so that should also be addressed.

**Review by NikkelM — CHANGES_REQUESTED** [review]
The pop-up now opens correctly, but the auto-complete window is still being displayed under the navigation-pane.

**Review by NikkelM — APPROVED** [review]

**Pull request merged**
