### PR TITLE
123 options page

### LINKED ISSUE #123: Options page
As an Admin, I want to see an options page as my starting point to manage the portal. As a signed in user I want to see an options page to edit personal information, contribute to the portal and so on. As a visitor, I want to get the option to sign in.

Screenshot 2022-01-04 at 22 52 41
Screenshot 2022-01-04 at 22 53 02
Screenshot 2022-01-04 at 22 53 22

# Details
- #122 makes sure, that you know what people are logged in, create a table, that marks some users as admins
- design the page with the round image and the options, no button needs functionality yet
- "Sign in as Max Mustermann/ Peter Admin" should not be a button in the options page, as this is a prototype functionality

### PR DESCRIPTION
**Pull request by tfiedlerdev**
Closes #123 
Adds a new route `/options`

Shows this page (for normal users): 
image
And a slightly different page for admin users
and this page if one is not signed in: 
image

Automatically detects which user is signed in or wether there is a user signed in at all

We currently found no way to test the view since we can't manipulate the global `user_signed_in` variable which influences the rendered contents as described above.

### CODE REVIEW

**Review by lucasliebe — APPROVED** [review]
I have looked through everythung. The code you added seems fine, but this all these edits are still very strange!

**Review by FranzSw — DISMISSED** [review]
Lets fix this git issue, if we commit this, all PRs will have merge cionflicts EVERYwhere

**Review by FranzSw — COMMENTED** [review]
Now, if Lucas is fine with it, I wont stop you from merging it :D

**Review by lucasliebe — APPROVED** [review]
changes made seem fine, approved for merge

**Pull request merged**
